## Append samples of your project ##
resources:
- governance_v1alpha1_agent.yaml
- governance_v1alpha1_agentpolicy.yaml
- governance_v1alpha1_agentbudget.yaml
- governance_v1alpha1_agentguardrail.yaml
- governance_v1alpha1_agenttrust.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
